---
# tasks/main.yml

- name: ocStore | Sync | Download files
  synchronize:
    archive: "yes"
    compress: "yes"
    mode: "pull"
    src: "{{ ocstore_www_root }}/{{ item.path }}/"
    dest: "{{ playbook_dir }}/{{ ocstore_sync_dir }}/{{ item.path }}/"
    rsync_opts: "{{ item.options | default([]) }}"
  with_items: "{{ ocstore_sync_download }}"
  become: yes

- name: ocStore | Sync | Upload files
  synchronize:
    archive: "yes"
    compress: "yes"
    mode: "push"
    src: "{{ playbook_dir }}/{{ ocstore_sync_dir }}/{{ item.path }}/"
    dest: "{{ ocstore_www_root }}/{{ item.path }}/"
    rsync_opts: "{{ item.options | default([]) }}"
  with_items: "{{ ocstore_sync_upload }}"
  become: yes
